databases:
  - name: room_share_matching_db
    databaseName: room_share_matching_db
    user: db_user
    region: singapore
    plan: starter

services:
  - type: web
    name: room_share_matching
    env: python
    region: singapore
    plan: starter
    branch: main
    buildCommand: "./build.sh"
    startCommand: "gunicorn matching.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: room_share_matching_db
          property: connectionString 
      - key: SECRET_KEY 
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
    autoDeploy: true