# Generated by Django 4.1.7 on 2023-04-09 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_alter_userroomlayout_layout'),
    ]

    operations = [
    ]
